### ISSUE TITLE
Core Error from HASS agent integration load

### ISSUE THREAD

**Issue by mahoromax** [LAB02-Research/HASS.Agent-Integration#53]
Found the following error in my protocols. And I can't make more out of it than that it happens on load. (Init, create task,...)
Might be related to an existing issue but I have no clue :D

```
Logger: homeassistant.util.logging
Quelle: util/logging.py:95
Erstmals aufgetreten: 16:22:50 (54 Vorkommnisse)
Zuletzt protokolliert: 16:49:29

Exception in updated when handling msg on 'hass.agent/devices/BB-8': '{"serial_number":"4e9d67b9-4fac-4ce8-bd51-600c5f33b821","device":{"identifiers":"hass.agent-BB-8","manufacturer":"LAB02 Research","model":"Microsoft Windows NT 10.0.22631.0","name":"BB-8","sw_version":"2022.14.0"},"apis":{"notifications":true,"media_player":true}}' Traceback (most recent call last): File "/config/custom_components/hass_agent/__init__.py", line 147, in updated hass.async_create_task(handle_apis_changed(hass, entry, apis)) File "/usr/src/homeassistant/homeassistant/core.py", line 805, in async_create_task self.verify_event_loop_thread("hass.async_create_task") File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'hass_agent' calls hass.async_create_task from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassasync_create_task at custom_components/hass_agent/__init__.py, line 147: hass.async_create_task(handle_apis_changed(hass, entry, apis)). Please report it to the author of the 'hass_agent' custom integration.
```

**Comment by 3mta3** [comment]
Appears this integration is no longer maintained, but has been forked - issue appears resolved in the new repository. I followed the instructions to install the 2.x windows agent and HACS integration from the fork: https://github.com/hass-agent

**Comment by mahoromax** [comment]
Oh wow, thank you. I had no idea, when I set it up it appears it was already abandoned, but it worked :D

If I wouldve checked any issue I mightve noticed :-/
